<?php

namespace Puth;

use PHPUnit\Event\Facade;
use PHPUnit\Event\Test\Failed;
use PHPUnit\Event\Test\FailedSubscriber;
use PHPUnit\Framework\TestCase;
use Puth\Traits\PuthAssertions;
use Puth\Traits\PuthTestCaseTrait;
use Throwable;

class PuthTestCase extends TestCase
{
    use PuthTestCaseTrait;
    use PuthAssertions;
    
    public function __construct(string $name)
    {
        parent::__construct($name);
        
        if (!$this->isPhpunitVersion(9)) {
            Facade::registerSubscriber(new class($this) implements FailedSubscriber {
                public function __construct(
                    protected PuthTestCase $puthTestCase,
                )
                {
                }
                
                public function notify(Failed $event): void
                {
                    $event->test()->
                    $this->puthTestCase->context->testFailed();
                    
                    if ($this->puthTestCase->shouldSaveSnapshotOnFailure()) {
                        $this->puthTestCase->context->saveContextSnapshot(['to' => 'file']);
                    }
                }
            });
        }
    }
    
    protected function onNotSuccessfulTest(Throwable $t): never
    {
        parent::onNotSuccessfulTest($t); // TODO: Change the autogenerated stub
    }
}