name: Release

on:
  push:
    branches:
      - client/php
#    tags:
#      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: get_version
        uses: battila7/get-version-action@v2
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 'Make release'
        run: ./bin/make-release.js version 0.0.1

      - name: Split php repo
        env:
          github_push_token: ${{ vars.PUSH_PUSH_SPLIT }}
        run: |
          echo ${{ vars.PUSH_PUSH_SPLIT }}
          echo $github_push_token
          PUTH_PUSH_SPLIT_TOKEN=$github_push_token ./bin/php-split.sh