name: Release

on:
  push:
    branches:
      - client/php
#    tags:
#      - 'v*'

jobs:
  build:
    - id: get_version
      uses: battila7/get-version-action@v2
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: 'Make release'
      run: ./bin/make-release.js version 0.0.1
      
    - name: Split php repo
      run: ./bin/php-split.sh