name: Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: get_version
        uses: battila7/get-version-action@v2
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PUTH_SPLIT_PUTH_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 'Make tag release'
        if: startsWith(github.ref, 'refs/tags/v')
        run: ./bin/make-release.js version ${{ steps.get_version.outputs.version-without-v }}
        
      - name: 'Make dev release'
        if: github.ref == 'refs/heads/master'
        run: ./bin/make-release.js version dev-master

      - name: Split php repo
        run: ./bin/php-split.sh