name: Tests
on:
  push:
    branches:
      - master
      - develop
      - feature/monorepo
  pull_request:
    branches: 
      - master

jobs:
  test:
    name: 'Node.js v${{ matrix.node-version }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14
          - 16
          - 18
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
      - uses: actions/checkout@v2
      - name: 'Cache'
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-node-v${{ matrix.node }}-
      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile
#          npx lerna link
      - name: Build
        run: npx lerna run build
      - name: Test
        run: npx lerna run test

  build-test:
    runs-on: ubuntu-latest
    steps:
#      - id: get_version
#        uses: battila7/get-version-action@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: actions/checkout@v2
#      - name: 'Cache'
#        uses: actions/cache@v2
#        with:
#          path: ~/.npm
#          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#          restore-keys: |
#            ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#            ${{ runner.os }}-node-
#      - name: Install
#        run: |
#          yarn set version berry
#          yarn
#          yarn plugin import workspace-tools
#          yarn workspaces focus --production puth
#          mv node_modules workspaces/puth/node_modules
#          npx lerna link
#      - name: Build
#        run: |
#          ls -lah
#          ls -lah node_modules
#          npx lerna run build
#      - name: Test
#        run: npx lerna run test
      - name: Build
        run: |
          yarn set version berry
          yarn plugin import workspace-tools
          yarn workspaces focus --production puth
          ls -lah
          ls -lah workspaces/puth
          ls -lah workspaces/puth/node_modules
          mv node_modules workspaces/puth/node_modules
          TAG=${{ steps.get_version.outputs.version-without-v }}
          echo "Tag: $TAG"
          cd workspaces/puth
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_REPOSITORY }}:$TAG