name: Tests
on:
  push:
    branches:
      - master
      - develop
      - client/php
  pull_request:
    branches: 
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            workspaces/puth/.cache
          key: node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: node
      - name: yarn install
        run: yarn

  test-puth-node:
    needs: build
    name: 'Test Puth (Node.js v${{ matrix.node-version }})'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14
          - 16
          - 18
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'
      - name: 'Cache'
        uses: actions/cache/restore@v3
        with:
          path: |
            .yarn/cache
            workspaces/puth/.cache
          key: node-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: lerna run build && lerna run postbuild
      - run: lerna run test

  build-test-image:
    runs-on: ubuntu-latest
    name: 'Build test image'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache/restore@v3
        with:
          path: |
            .yarn/cache
            workspaces/puth/.cache
          key: node-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: lerna run build && lerna run postbuild
      - name: Image
        run: |
          yarn workspaces focus --production puth
          rm -rf workspaces/puth/node_modules
          mv node_modules workspaces/puth
          cd workspaces/puth
          docker build --file Dockerfile --tag puth-test-image .
      - name: Test image
        run: |
          yarn
          docker run -d -p 7345:7345 puth-test-image
          PUTH_URL=http://127.0.0.1:7345 lerna run test:only:remote
          docker save --output=/tmp/puth-test-image.tar puth-test-image
          ls -lah /tmp
      - uses: actions/upload-artifact@v2
        with:
          name: puth-test-image
          path: /tmp/puth-test-image.tar

  test-client-laravel:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: puth-test-image
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/puth-test-image.tar
          docker image ls -a
