name: Tests
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  test:
    name: 'Node.js v${{ matrix.node-version }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 10
          - 12
          - 14
          - 15
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
      - uses: actions/checkout@v2
      - name: 'Cache node_modules'
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v${{ matrix.node }}-
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - run: yarn run build
      - name: Run All Node.js Tests
        run: yarn test

  build-test:
    runs-on: ubuntu-latest
    steps:
      - id: get_version
        uses: battila7/get-version-action@v2
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          TAG=${{ steps.get_version.outputs.version-without-v }}
          echo "Tag: $TAG"
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_REPOSITORY }}:$TAG