name: Tests
on:
  push:
    branches:
      - master
      - develop
      - feature/monorepo
  pull_request:
    branches: 
      - master

jobs:
  test:
    name: 'Node.js v${{ matrix.node-version }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14
          - 16
          - 18
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'
      - name: 'Cache'
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-node-v${{ matrix.node }}-
      - name: Install Dependencies
        run: |
          yarn
      - name: Build
        run: lerna run build
      - name: Test
        run: lerna run test

  build-test:
    runs-on: ubuntu-latest
    steps:
      - id: get_version
        uses: battila7/get-version-action@v2
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 'Cache'
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-node-v${{ matrix.node }}-
      - name: yarn build
        run: |
          yarn
          lerna run build
          lerna run postbuild
      - name: Install Dependencies
        run: |
          yarn workspaces focus --production puth
          rm -rf workspaces/puth/node_modules
          mv node_modules workspaces/puth
          TAG=${{ steps.get_version.outputs.version-without-v }}
          echo "Tag: $TAG"
          cd workspaces/puth
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_REPOSITORY }}:$TAG